# Generated by Django 2.0.5 on 2018-05-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorns_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.ManyToManyField(to='unicorns_blog.Categorie'),
        ),
    ]
