# Generated by Django 2.0.5 on 2018-06-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorns_blog', '0003_auto_20180528_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(max_length=50, verbose_name="Contenu de l'article"),
        ),
    ]
