# Generated by Django 2.0.5 on 2018-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicorns_blog', '0004_auto_20180625_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(max_length=2000, verbose_name="Contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=50, verbose_name="Titre de l'article"),
        ),
    ]
